# Using container-based infrastructure
# sudo: false
# enable trusty beta
sudo: required
dist: trusty

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src
        - $HOME/x-tools
        # - $HOME/zlib-install
        # - $HOME/openssl-install
        # - $HOME/pcre-install
        # - $HOME/libsodium-install
        # - $HOME/mbedtls-install
        # - $HOME/libev-install


# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            # - libncurses5
            # - libncurses5-dev
            # - libncursesw5
            # - libncursesw5-dev
            - texinfo
            - help2man
            - asciidoc
            - xmlto
            - libgmp-dev
            - nettle-dev
            # - libtool
            # - autogen
            # - automake
            - libstdc++6
            - lib32stdc++6
            - net-tools
            - perl
            # - python

            - gcc-multilib
            - g++-multilib
            - lib32z1-dev
            - libxml2-dev
            # - gconf
            # - pkg-config
            # - uuid-dev

            - libelf1:i386
            - libltdl-dev

            # - lzma-dev
            # - lzma
            # - liblzma-dev
            # - liblzma5

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
# before_install:
    # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    # - git submodule update --init --recursive
    # - sudo apt-get update -qq
    # - sudo apt-get install libpcre3 libpcre3-dev -y

# Building crosstool-NG core
# keep these on at all times because it is fast
install:
    - pwd

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    matrix:
        # - export PATH=$HOME/x-tools/mipsel-unknown-linux-uclibc/bin:$PATH
        # - BROADCOM_SDK=6

        - TT_BUILD=r2e       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2c       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2d       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2g       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2u       BROADCOM_SDK=src-rt
        - TT_BUILD=r2t       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2b       BROADCOM_SDK=src-rt
        # - TT_BUILD=r2o       BROADCOM_SDK=src-rt
        - TT_BUILD=r2z       BROADCOM_SDK=src-rt
        - TT_BUILD=r2a       BROADCOM_SDK=src-rt
        - TT_BUILD=r2v       BROADCOM_SDK=src-rt
        - TT_BUILD=r2m       BROADCOM_SDK=src-rt
        - TT_BUILD=r2i       BROADCOM_SDK=src-rt
        - TT_BUILD=r2j       BROADCOM_SDK=src-rt
        - TT_BUILD=r2f       BROADCOM_SDK=src-rt

        - TT_BUILD=f5d       BROADCOM_SDK=src-rt
        - TT_BUILD=f7d       BROADCOM_SDK=src-rt

        - TT_BUILD=e1000v2f BROADCOM_SDK=src-rt
        - TT_BUILD=e1000v2i  BROADCOM_SDK=src-rt
        - TT_BUILD=e1200v1f  BROADCOM_SDK=src-rt
        - TT_BUILD=e1200v1i  BROADCOM_SDK=src-rt

        - TT_BUILD=n60e     BROADCOM_SDK=src-rt
        - TT_BUILD=n60c      BROADCOM_SDK=src-rt
        - TT_BUILD=n60d      BROADCOM_SDK=src-rt
        - TT_BUILD=n60g      BROADCOM_SDK=src-rt
        - TT_BUILD=n60t      BROADCOM_SDK=src-rt
        - TT_BUILD=n60b      BROADCOM_SDK=src-rt
        - TT_BUILD=n60o      BROADCOM_SDK=src-rt
        - TT_BUILD=n60z      BROADCOM_SDK=src-rt
        - TT_BUILD=n60i      BROADCOM_SDK=src-rt
        - TT_BUILD=n60j      BROADCOM_SDK=src-rt
        - TT_BUILD=n60v      BROADCOM_SDK=src-rt
        - TT_BUILD=n60m      BROADCOM_SDK=src-rt

        - TT_BUILD=n64e     BROADCOM_SDK=src-rt
        - TT_BUILD=n64c      BROADCOM_SDK=src-rt
        - TT_BUILD=n64d      BROADCOM_SDK=src-rt
        - TT_BUILD=n64g      BROADCOM_SDK=src-rt
        - TT_BUILD=n64u      BROADCOM_SDK=src-rt
        - TT_BUILD=n64t      BROADCOM_SDK=src-rt
        - TT_BUILD=n64b      BROADCOM_SDK=src-rt
        - TT_BUILD=n64o      BROADCOM_SDK=src-rt
        - TT_BUILD=n64v      BROADCOM_SDK=src-rt
        - TT_BUILD=n64m      BROADCOM_SDK=src-rt

        - TT_BUILD=rtn53    BROADCOM_SDK=src-rt
        - TT_BUILD=f9k       BROADCOM_SDK=src-rt
        - TT_BUILD=e2500     BROADCOM_SDK=src-rt
        - TT_BUILD=e3200     BROADCOM_SDK=src-rt
        - TT_BUILD=n6        BROADCOM_SDK=src-rt
        - TT_BUILD=n60       BROADCOM_SDK=src-rt
        - TT_BUILD=wndr64    BROADCOM_SDK=src-rt
        - TT_BUILD=wndr64-vpn BROADCOM_SDK=src-rt

        - TT_BUILD=v2e       BROADCOM_SDK=src-rt
        - TT_BUILD=v2z       BROADCOM_SDK=src-rt

        - TT_BUILD=r64e      BROADCOM_SDK=src-rt
        - TT_BUILD=r64z      BROADCOM_SDK=src-rt

        - TT_BUILD=ac66e       BROADCOM_SDK=src-rt
        - TT_BUILD=ac66z       BROADCOM_SDK=src-rt
        - TT_BUILD=w1800re     BROADCOM_SDK=src-rt
        - TT_BUILD=w1800rz     BROADCOM_SDK=src-rt
        - TT_BUILD=r6300e      BROADCOM_SDK=src-rt
        - TT_BUILD=r6300z      BROADCOM_SDK=src-rt
        - TT_BUILD=wndr4500e   BROADCOM_SDK=src-rt
        - TT_BUILD=wndr4500z   BROADCOM_SDK=src-rt
        - TT_BUILD=wndr4500v2e BROADCOM_SDK=src-rt
        - TT_BUILD=wndr4500v2z BROADCOM_SDK=src-rt
        - TT_BUILD=n80o        BROADCOM_SDK=src-rt


        # # include:
        # #     - BROADCOM_SDK=6
        # - TT_BUILD=r64e BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=r64z BROADCOM_SDK=src-rt-6.x

        # - TT_BUILD=ac66e BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=ac66z BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=w1800re BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=w1800rz BROADCOM_SDK=src-rt-6.x

        # - TT_BUILD=r6300e BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=r6300z BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=wndr4500e BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=wndr4500z BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=wndr4500v2e BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=wndr4500v2z BROADCOM_SDK=src-rt-6.x
        # - TT_BUILD=n80o BROADCOM_SDK=src-rt-6.x


    global:
        - secure: UD3vvaHojShwoPlpJPKx34eGPav+R1/9+RhPXTH8sGhikd+buIj4UWiFgyAYT6Kh4AZceeLcS8YiEMH8lbzGZEh1tZofaQ/es4p0cWiP612hVI1PWimcWzoCztWte9YNAQ4I+gBnvScW1xPWqzplcUk0XlOYSYLq32PM7HPPV8hD0xfzrDsOdtq32bzbsT2xXM0flp00Lyb72XrU8aQz8yWs0d2VCneGR7QJdf/tx+ki2tqIYGO/AEm79wG4D03O76wQ/vOvsRoTKuh868patH6ai4ol7CoUlJw91fSlnTf+GL+Z0Mb8H4nWO/61uTxE/uXv4jtq5RIdX00dHl9rkcEQaBi5+ZeKYXv5WvVTgxdFc4BHhNOjQszIS81qenLUqgcDd4HMoc0VJ3L/JkXyhqLey5aiHIjz4eAuWbRFBxscQ933s84Rap5l88FEnvqmr25Q5hIO1kwykRY/8H5LIwcugRB+6upEiwfi9c0AURnmNzqo/52jUytPRL8aR774h9P2tTRD7/OhNzP1rPd87og1yILJqW5SbBcPAsXwDEoFPALRVmLrYIvw2l4mbBRzSwNZWuPmDP5DF0lacXlZPhLd2GQRm0jTnfAUYeZKTNXdPjmSWt2lLYkyp5b7O6W3palH6+u5IAKCphVjxTwH3FxTBSlXZOpriIqFr2R+Ydw=

# Building the standard samples
script:
    # - . ls -l $HOME
    - sudo apt-get remove uuid-dev
    - . $TRAVIS_BUILD_DIR/.travis.sh      # Load the travis environment
    - echo ============================
    - pre_build_prep # > /dev/null
    - build_tomato

# On failure displaying the last lines of the log file
after_failure:
    - echo ============= tomato ===============
    - tail -n 1000 ~/tomato.txt


after_success: . $TRAVIS_BUILD_DIR/update-gh-pages.sh
